
##############################
#  Visualization             #
#  Maya Khalifé, CEA 2015    #
##############################
/vis/open OGLSQt #800x600-0+0
#/vis/open OGLSX
/vis/viewer/set/viewpointThetaPhi 45 45
/vis/viewer/zoom 3
/vis/drawVolume
#/vis/scene/add/axes
#/vis/viewer/flush
#/tracking/verbose 0
/tracking/storeTrajectory 1
/vis/scene/add/hits   1	
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate -1
/vis/viewer/scale


